### ISSUE TITLE
WCFService creates a separate WCF endpoint for each WCF operation

### ISSUE THREAD

**Issue by webcentralpa** [Particular/NServiceBus.Host#43]
Currently, WCFService creates a separate WCF endpoint for each NServiceBus Handler. Each of these endpoints has a single method corresponding to the NServiceBus Handler.

It would be useful to allow multiple WCF methods within a single WCF endpoint, with each method corresponding to an NServiceBus Handler.

This was also requested in a Google Group topic: https://groups.google.com/forum/#!topic/particularsoftware/6gcDZOW4RZc

**Comment by DavidBoike** [comment]
This is definitely something that, I believe, would add value. I think we'd definitely welcome a PR along those lines, as you mentioned in your email to @johnsimons.

Do you have any ideas for what a possible API might look like? 

One complication is that part of the vision is to move WcfService out of the Host and into its own NuGet package, so that you wouldn't necessarily need the Host to create one, and because it depends upon callbacks which have already been moved out of the Core. But I am assuming you'd like to accomplish this within V5, so those dependencies would just need to be managed accordingly. Correct?

**Comment by DavidBoike** [comment]
@webcentralpa Take a look at this pull request Particular/docs.particular.net#868 (created by our own @SimonCropp) that may make the NServiceBus.Host WCF implementation unnecessary.

What do you think?

**Comment by webcentralpa** [comment]
From a quick look, it seems that this would be a good replacement for the NServiceBus.Host WCF implementation. 

If I understand it correctly, this PR would create a single WCF endpoint which would contain all of the WCF operations. This would be preferable to how it works currently (a bunch of WCF endpoints, each with a single operation.)

**Comment by DavidBoike** [comment]
@webcentralpa Thanks for the feedback! How would you feel if it was _only_ provided as a sample (which would allow you to tweak all the bits to your heart's content) and removed from the NServiceBus codebase altogether?

**Comment by webcentralpa** [comment]
The project that I'm working on is for a large client that is purchasing commercial licenses for NServiceBus. We would like to use as much of the standard NSB functionality as possible. 

Having this code as a sample is OK, but we would prefer if it were part of the NServiceBus codebase.

Either way, we always have the option of just creating a WCF service manually and including the NSB NuGet package. The built-in WCF functionality just seemed like a simpler way of doing it.

**Comment by SimonCropp** [comment]
@webcentralpa 

Shipping a dll and a nuget has several drawbacks when compared to a sample. If you own the integration between WCF and NSB you get the following benefits

 * easier to debug since the code, and any problems, will be immediately visible 
 * allows you to fully customize your use of the WCF API rather then being forced down the one abstraction we choose. 
 * you can control how the WCF service is hosted, 
 * you can control the url structure that is used
 * you can control the binding method
 * you can control easily inject validation on for any incoming request
 * add any custom logging u want

etc

As for "built-in WCF functionality just seemed like a simpler"... take a look at the two main classes that enable you to map NSB to WCF
http://docs.particular.net/samples/web/wcf-callbacks/#wcf-helpers-receiving-endpoint-helpers-wcf-mapper
http://docs.particular.net/samples/web/wcf-callbacks/#wcf-helpers-receiving-endpoint-helpers-callbackservice
In total it is less than 100 lines of code.

So there are positives and negatives to both approaches. In light of how easy it is for someone to own their own integration it does not seem valuable enough to bundle that code into a nuget.

**Comment by webcentralpa** [comment]
You make some good points there Simon. I can see how it would not be valuable enough to bundle this into a nuget package.

As you suggested, we have decided to do our own WCF integration for the project that I'm working on. Thanks for your help.

**Comment by SimonCropp** [comment]
@webcentralpa good to hear. let me know if i can finesse the sample in any way based on your custom integration
