### ISSUE TITLE
Timebox the shutdown to prevent the windows service from hanging

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Host#51]
At the moment we call "bus.Stop" syncronously. Since bus.Stop can hang indefinitely this means that we can't guarantee that the windows service will stop at all times. This behavior prevents service recovery to kick in and also confuses users that might belive that the service is running while its in a half stopped state.

I propose that we time box the shutdown and give up after lets say 30 seconds to allows the service to go down and be restarted.

There is a global flag that can be set (@gbiellem please add link) to tell the OS to always kill the service after a given time but since that is not on by default we should be safe and timebox instead. We should still add doco to highlight and recommend this flag.

**Comment by gbiellem** [comment]
@andreasohlund the  global flag is a reg key called  [WaitToKillService](https://technet.microsoft.com/en-us/library/cc976045.aspx) timeout.  This is only applicable on system shutdown.  So it wouldn't help on a manual service stop.  This flag basically controls how long to wait before prompting with a dialog which asks if it is ok to shutdown even if service(s) haven't stopped.  You can combine this with another registry flag called  [AutoEndTask](https://technet.microsoft.com/en-us/library/cc978604.aspx) which has to be applied to the default user profile.  Adding that setting means the kill timer doesn't bother with the dialog and just automatically shuts down.  As you pointed out these are system wide settings so I highly recommend we not screw with them.

Another option we could explore  is to request more time when it looks like the service isn't going to stop cleanly after the default amount of time.   This is covered [here}(https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicebase.requestadditionaltime.aspx)

**Comment by andreasohlund** [comment]
@Particular/nservicebus I propose we treat this as a patch since this can cause production issues due to not allowing service restarts to kick in. Thoughts?

**Comment by timbussmann** [comment]
so is this comment https://github.com/Particular/NServiceBus/pull/3254#issuecomment-170863495 not true and windows services don't auto kill the process after 90 sec?

**Comment by andreasohlund** [comment]
According to @gbiellem the auto kill only happens on machine shutdown if you have enable it in the registry and the behavior reported by the user confirms this

**Comment by andreasohlund** [comment]
This is one way of timeboxing the shutdown - https://github.com/Particular/NServiceBus/pull/3254#issuecomment-171070251

**Comment by andreasohlund** [comment]
@timbussmann see http://stackoverflow.com/a/29928342/236004

**Comment by andreasohlund** [comment]
Here's a sample that uses a custom satellite, we can use to tho try to repro the hanged shutdown https://github.com/Particular/docs.particular.net/tree/master/samples/sql-bridge/Version_5/SqlBridge

**Comment by andreasohlund** [comment]
@dvdstelt do we have any doco on shutdown that needs to be updated to claridy that bus.Shutdown is not guaranteed to return?

@SimonCropp Should we update the bootstrap nuget to handle this properly as well?

**Comment by SimonCropp** [comment]
@andreasohlund how would u code that?

**Comment by andreasohlund** [comment]
@SimonCropp this is one way https://github.com/Particular/NServiceBus/pull/3254#issuecomment-171070251, but let's wait and see what this fix ends up like?

**Comment by mauroservienti** [comment]
should we consider this in scope for V6? if yes, could you please ad the expected `Tag: Core V6` label? cheers.

**Comment by andreasohlund** [comment]
We're fixing it in the production version so it will be included in the "v6" version as well. No need to tag it IMO

**Comment by ramonsmits** [comment]
So we normally do a gracefull shutdown. If a customer has a message handlers that is still busy this handler will now be killed. Meaning, any handler or task running for more then 30 seconds might cause issues. Especially if running without transactions. This could effect customers that have such long running tasks. Meaning, there could be valid reasons for the shutdown to take more then 30 seconds.

This should be addressed in the announcement.

Also, might we want to make this number configurable with even the option to disable it (wait indefinitely)?

**Comment by dvdstelt** [comment]
The configuration is a good point, but the entire issue is about not being able to gracefully shut down.

Also, @andreasohlund the codebase for V6 has changed so much that I can't cherry-pick the commits and move them over to V6. I'll wait for #52 to be merged, and then quickly add it to `develop` V6 branch. Which is weird, because this is NSB.Host 6.0 but when talking about V6 we're referring to the overal NServiceBus release. :)

**Comment by andreasohlund** [comment]
Good point @ramonsmits but it also depends on the transports, I checked and MSMQ in v5 would wait indefinitely but v6 will stop after 30 seconds.

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L80

Are we happy with this behavor?

How does the other transports behave? (cc @Particular/tf-async-transport )

**Comment by SeanFeldman** [comment]
@andreasohlund is 30 seconds a time that all transport should respect and comply with?

**Comment by dvdstelt** [comment]
Some options, which weren't discussed before

- Have the time configurable
- The ability to request for more time to shutdown

I think (almost) everything is also configurable through code with NServiceBus. Now I afaik the host does not have any configuration, just command-line parameters. So either add configuration, which isn't included yet. I'm not familiair with config, so could use some help if it's easy (and wise) to set this up in the host. But how about doing it on code? Should that be added as well for people who don't like app.configs?

About requesting additional time. The solution will become quite complex for a problem hopefully not too many people will run into. Because we'll have to allow it to get to 20 seconds, then request a timeout a few times and then wait until the entire time is up again. In the end we'll still have to be able to quite it after our x-step timeout completes, because currently it indefinitely hangs at points.

**Comment by bording** [comment]
Currently, it looks like both the v5 and v6 versions of the RabbitMQ transport just wait indefinitely for all in-flight messages to finish processing. There is no time-based element that I can see.

**Comment by andreasohlund** [comment]
>* Have the time configurable
* The ability to request for more time to shutdown

I'd say we consider this out of scope for now?

**Comment by dvdstelt** [comment]
I'd agree. And I also would not want customers to think that they can extend the shutdown time for when the server is rebooting, by altering NSB config. That's based on the registry setting, and from what I understand cannot be extended.

**Comment by gbiellem** [comment]
@dvdstelt  agreed

>  from what I understand cannot be extended.

that's not strictly true.  Individual services can ask for more time to start/stop etc - https://msdn.microsoft.com/en-us/librarysystem.serviceprocess.servicebase.requestadditionaltime.aspx

**Comment by dvdstelt** [comment]
> that's not strictly true. Individual services can ask for more time to start/stop

Also on shutdown?

**Comment by gbiellem** [comment]
> Also on shutdown?

Sorry my bad. I thought you meant service shutdown not system shutdown.  For system shutdown I believe it ignores that call.  On older OSes it repected it but around the Vista time frame shutdown got a bit more forceful

**Comment by tmasternak** [comment]
v6 of Sql transport waits for [30s](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/MessagePump.cs#L59) just as MSMQ

**Comment by andreasohlund** [comment]
>V5 (as far as I can tell) does not have any timeout. V6 of Sql transport waits for 30s just as MSMQ

@tmasternak can you bring this back to @Particular/tf-async-transport and make sure we highlight this in the upgrade guide (both sql and msmq) and perhaps add this behavior to the doco for each transport?

**Comment by tmasternak** [comment]
@andreasohlund: :+1:

**Comment by johnsimons** [comment]
Still confused why is MSMQ and Sql transport timeboxing, isn't this a host concern that we are discussing ?

**Comment by ramonsmits** [comment]
I agree with @johnsimons that its strange that each transport has its own shutdown/stop strategy. This should be controlled by the core. The host could influence the core to either wait indefinitely or for a configured amount of time.

In this case its clear that a 'stop' can be extended by the (windows service) host and the 'shutdown' cannot. Only the host can make this differentiation and is able to instruct the core how to behave and when to abort just before the environment will going to kill the process to log this condition.

For V5 this is out of scope but should it be out of scope for V6? I can assume that hosting in IIS or Azure has different stop/shutdown behavior.

Should the announcement reflect this breaking behavior?

Should the doco mention stop/shutdown behavior for the NServiceBus.Host and possibly link to MSDN info regarding those defaults?

By the way, we can *read* the *WaitToKillServiceTimeout* regkey with the configured max shutdown time and adjust the wait time. This to make sure that our wait time is not longer that the environment value. If the environment allows for a 5 minutes shutdown then why should we force 30 seconds and vice versa?

**Comment by dvdstelt** [comment]
I've added code to read it from registry and hopefully made it pretty safe so that when there's a weird value, there's no value or you're not allowed to read from there, it will return 30 seconds.
I added this code specifically to the WindowsHost and not GenericHost so that the latter can be used anywhere. But GenericHost has hard-coded value of 30.
By the way, on my WIn10 machine, the shutdown time is 5 secs! :)

**Comment by andreasohlund** [comment]
>By the way, we can *read* the *WaitToKillServiceTimeout* regkey with the
configured max shutdown time and adjust the wait time.

Is this really correct, this setting is only relevant when the machine is
shutting down/rebooting, and the case we have here is when the windows
service is stopped "manually" for some reason?

**Comment by andreasohlund** [comment]
Since we all agree its up to the host to decide how long we wait I propose we:

* change the transports to wait indefinitely for messages in flight to be processed
* document that bus.Stop is not guaranteed to return and that its up to the host to stop waiting when it decides that time is up

Thoughts?

**Comment by dvdstelt** [comment]
> change the transports to wait indefinitely for messages in flight to be processed
For transports using leases on messages, like Azure ServiceBus, what does this result in there, @yvesgoeleven?
For transports that can place really hard locks on messages, like SQL Transport, would that not mean the lock would be there indefinitely, until the host is stopped?

**Comment by andreasohlund** [comment]
Perhaps we can say that it's up to the transports to decide on how long they wait but the core will assume that it can take forever?

**Comment by dvdstelt** [comment]
For me to understand it, do you mean
- transports might decide to kill it after a certain amount of time.
- the core never interferes with this.
- the host, when stopping/shutting-down, will eventually kill after 30 seconds (based on `WaitToKillServiceTimeout`), no matter what?

I think we need to use `WaitToKillServiceTimeout` because
- we are not aware if the host is stopping or shutting down
- stuff might hang indefinitely, because not all transports might kill it after a certain amount of time.
- we don't want users to think that setting an NServiceBus specific configuration-setting, influences the time Windows allows a service to stop, upon rebooting.

**Comment by andreasohlund** [comment]
>I think we need to use WaitToKillServiceTimeout because

If we're not shutting down we have more time if we want since it only applies to shutdowns. And if we are shutting down it won't matter if we hang since we'll get killed no matter what?

I guess the upside is that the `WaitToKillServiceTimeout ` will act as a way for users to control how long we wait. But since that setting is machine wide it feels a bit useless?

**Comment by dvdstelt** [comment]
> But since that setting is machine wide it feels a bit useless?
Good point.

So always try to get more time in the host. And if we're on shutdown, we'll get killed nonetheless.
Does that mean we want a configurable amount of time after all?

As a side note, does this mean we're postponing this version, or is this for NSBv6?

**Comment by dvdstelt** [comment]
Funny to see how a 'bug' this simple can turn into a discussion like this. Not that it's bad, because now we get to think about it really well.

**Comment by danielmarbach** [comment]
So we know that reading registry makes us break potential dotnet core
compatibility even more but still we continue arguing in that direction?

**Comment by boblangley** [comment]
Not sure this fits here, but does the IMessageHandlerContext get a reference to a CancellationToken so we can also allow the user to handle shutdown scenarios in the handler? Is this advised?

**Comment by danielmarbach** [comment]
Bob, technically it is available but not exposed yet. The scenario you
described was the intention

**Comment by mauroservienti** [comment]
> If we're not shutting down we have more time if we want since it only
applies to shutdowns.

I'm not so sure. The service control manager forces a service to respect
startup and shutdown constraints even if the system is not shutting down.
IIRC.

> And if we are shutting down it won't matter if we hang since we'll get
killed no matter what?

A clean shutdown is always better than a dirty one.

The point that Daniel is raising is very good.

On Tue, Feb 2, 2016, 15:58 Daniel Marbach <notifications@github.com> wrote:

> So we know that reading registry makes us break potential dotnet core
> compatibility even more but still we continue arguing in that direction?
>
> On Tuesday, February 2, 2016, Andreas Öhlund <notifications@github.com>
> wrote:
>
> > >By the way, we can *read* the *WaitToKillServiceTimeout* regkey with the
> > configured max shutdown time and adjust the wait time.
> >
> > Is this really correct, this setting is only relevant when the machine is
> > shutting down/rebooting, and the case we have here is when the windows
> > service is stopped "manually" for some reason?
> >
> > On Tue, Feb 2, 2016 at 1:55 PM, Dennis van der Stelt <
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I've added code to read it from registry and hopefully made it pretty
> > safe
> > > so that when there's a weird value, there's no value or you're not
> > allowed
> > > to read from there, it will return 30 seconds.
> > > I added this code specifically to the WindowsHost and not GenericHost
> so
> > > that the latter can be used anywhere. But GenericHost has hard-coded
> > value
> > > of 30.
> > > By the way, on my WIn10 machine, the shutdown time is 5 secs! :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Particular/NServiceBus.Host/issues/51#issuecomment-178559068
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Particular/NServiceBus.Host/issues/51#issuecomment-178579305
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.Host/issues/51#issuecomment-178616666>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by andreasohlund** [comment]
>I'm not so sure. The service control manager forces a service to respect
startup and shutdown constraints even if the system is not shutting down.

Think we need to test this to be sure, @gbiellem stated that it only applies to shutdown and the doco seems to be implying the same:  "Determines how long the system waits for services to stop after notifying the service that the system is shutting down"

I'm still not convinced that reading the regkey adds enough value.

How about we scope that out to not derail this pull and keep the changes to a minumum since we're targeting a 6.0.1? (we can debate the regkey for the 7.0.0 version?)

>So we know that reading registry makes us break potential dotnet core
compatibility even more but still we continue arguing in that direction?

@danielmarbach  Agreed in general but this is the "nservicebus windows host" so I'd say this is less important in this context? (or does dotnetcore plan to support the concept of a "windows service" cross plat?)

**Comment by bording** [comment]
I spent a little bit of time looking into this yesterday.

From what I read, there are two different scenarios:

1. The service is being shutdown via the Service Control Manager (SCM)
2. The service is being shutdown because Windows is shutting down.

For scenario 1, there is a certain amount of time in which you have to finish the shutdown process before the SCM will indicate that the service has stopped responding. This scenario is where the `RequestAdditionalTime()` method comes in. You can call this if you need more time, and it will tell the SCM to give the service more time before it marks it as not responding. There is a maximum amount of time you can request before it marks it as not responding regardless of how much additional time you've requested. In the documentation I saw, it said the default time was 30 seconds, with a maximum of 125 seconds that you can request. It would be a good idea to verify this, since these seem like the sort of things could change in different versions of Windows.

For scenario 2, that is where the `WaitToKillServiceTimeout` registry key comes into play. When windows is shutting down, there is a fixed amount of time that Windows will wait. In older versions of Windows, it would then display a dialog about the service not shutting down properly and give you an option to kill the process or abort the shutdown. In newer versions of Windows, the timeout is now how long it will wait until it just kills the process and finishes shutting down.

The `WaitToKillServiceTimeout` registry key is what controls this timeout value, and the default value has drastically decreased in newer versions of Windows. In Windows 10, it appears to be 5 seconds.

From what I can tell, `WaitToKillServiceTimeout` has no meaning for scenario 1.

**Comment by asednev** [comment]
> The service is being shutdown via the Service Control Manager (SCM)

As it stands right now, if service is being shutdown via SCM, it can hang indefinitely on Windows Server 2008 R2 and Windows Server 2012. So request for additional time certainly is not enforced by SCM. I had instances when service won't shut down for 40 minutes (way more than maximum of 125 seconds)

**Comment by bording** [comment]
> So request for additional time certainly is not enforced by SCM.

AFAIK, SCM won't actually shut a service process down, it will just mark it not responding if it doesn't finish the shutdown process in the requested amount of time.

**Comment by johnsimons** [comment]
Agree with @bording, in those scenarios @asednev, it is up to the user to kill the process

**Comment by asednev** [comment]
@johnsimons isn't that is what this issue all about? User shouldn't kill the process controlled by SCM. The process should shutdown gracefully.

**Comment by johnsimons** [comment]
@asednev yes if everything is good that is what should happen, but in the circunstances that the endpoint takes longer to shutdown (this could happen based on many unknowns) and SCM flags it as unresponsive, I would say that then it is up to the user to make an educated decision to kill the process.

**Comment by andreasohlund** [comment]
Rereading all this, I'm starting to doubt this as well. 

My statement

>This behavior prevents service recovery to kick in and also confuses users that might belive that the service is running while its in a half stopped state.


Is wrong since when we hit a critical error and want to host to crash and recover we don't do a bus.Stop (needs to be double checked), but instead an `Environment.FailFast`

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/GenericHost.cs#L127

So the hang only happens when you manually stops the service. While this is not good of course I'm no longer sure we should just timebox it?

The root cause of the hang (in this current scenario) is being dealt with here:

https://github.com/Particular/NServiceBus.RavenDB/issues/140

and is also somewhat related to the core not timeboxing satellite shutdowns:

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Satellites/SatelliteLauncher.cs#L70

**Comment by ramonsmits** [comment]
We are talking about the WIndows Service Host here that reads the registry key. That is pretty normal thing to do for a windows service as it is a native concept of its environment. The Windows Service host is also able to know the difference between a stop and a shutdown but this might not be properly exposed by TopShelf. For a normal stop operation I would not read the registry key and try to extend/delay the regular stop. But all this I see as possible enhancement for V6, not as a bug for V5. The Windows Service Host must behave pretty native. 

I think Dennis is current approuch, reading the regkey and using that value is good for a V5 enhancement/patch and the rest should probably be put in a new issue?

**Comment by dvdstelt** [comment]
> So the hang only happens when you manually stops the service. While this is not good of course I'm no longer sure we should just timebox it?

Because? Are exceptions and `Environment.FailFast` shutdowns now also timeboxed, you mean? Because machine shutdowns timeboxed anyhow, just not by us.

**Comment by andreasohlund** [comment]
>Are exceptions and Environment.FailFast shutdowns now also timeboxed, you
mean?

Yes when you "fail fast" the process is terminated immediately

https://msdn.microsoft.com/en-us/library/ms131100(v=vs.110).aspx

**Comment by dvdstelt** [comment]
@ramonsmits raised an interesting issue in a Zoom call...

We currently terminate the endpoint instance and whatever it was doing after a certain amount of time. Perhaps someone from operations should kill the process instead of us, deciding for them, to kill _their process_. Instead we read from the registry how much time we have and report 3 times before our time is up, so devs/ops know why the endpoint instance was terminated.

A couple of thoughts on this.

1. They should be monitoring services for not shutting down. You could argue operations should always be monitoring critical Windows Services, but of course not everyone is doing this.
2. Having operations kill processes on production machines is always dangerous, simply because humans make mistakes. Especially if you can't figure out which process to kill, when so many services running.
3. It's the old behavior of not terminating the process, but we now do make clear to devs/ops that we tried, but did not succeed, in the logs.

We need to make a decision on merging this, or taking out shutting it down and just log 3 times within the time window we think we have.

**Comment by danielmarbach** [comment]
Everytime we decided to kill on behalf of the user this has bitten us. For example critical error action should ring a bell ;)

**Comment by andreasohlund** [comment]
>Everytime we decided to kill on behalf of the user this has bitten us.

Not sure, I'd say us silently doing a bus.Stop on critical error in the core has caused a large amounts of 

"My web site doesn't process any messages but is still running" desk cases. Yes they should have read their logs better but we all know that isn't happening...


So are we happy by fixing the ravendb bug and leave it at that?

Or should we also consider not allowing satellites to hang shutdown indefinitely?

**Comment by asednev** [comment]
> "My web site doesn't process any messages but is still running" desk cases. Yes they should have read their logs better but we all know that isn't happening...

I side with @andreasohlund that when NSB Host process is running but not processing anything and no errors written to logs, it begs question of what is it doing. 

Please consider setting process shutdown timeout as an optional setting. Options could be configured to terminate process, log error, or not doing anything when shutdown timeout elapses. Default could be not doing anything.

**Comment by andreasohlund** [comment]
>that when NSB Host process is running but not processing anything and no errors written to logs, it begs question of what is it doing.

http://docs.particular.net/nservicebus/hosting/critical-errors#default-action-handling-in-nservicebus

Just to clarify: that behavior is default when you self host. When using the NServiceBus.Host.exe a critical error will cause the process to be killed (Environment.FailFast) and service recovery will kick in if setup properly

http://docs.particular.net/nservicebus/hosting/critical-errors#default-action-handling-in-nservicebus-host

**Comment by dvdstelt** [comment]
We had a meeting about this today. It was decided to drop this entirely in NSB.Host V6 because there are just too many side effects and stuff that can bite us upon release.

This did raise some good discussions though, so we're raising two new issues:
https://github.com/Particular/NServiceBus.Host/issues/56
https://github.com/Particular/docs.particular.net/issues/1167
