### ISSUE TITLE
Split `IWantToRunWhenEndpointStartsAndStops`

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.Host#69]
Split into two interfaces.

`IWantToRunWhenEndpointStarts`
`IWantToRunWhenEndpointStops`

Most use cases do not require both. Interface segregation can clean up a lot of no-op methods for users.

If we are breaking this functionality out from core for v6, I propose we include this change for v6.

The upgrade guide is still minimal: Replace `IWantToRunWhenBusStartsAndStops` with `IWantToRunWhenEndpointStarts` and `IWantToRunWhenEndpointStops`

**Comment by SimonCropp** [comment]
how would this work for instances that track something that needs to be clean up?

**Comment by bording** [comment]
> how would this work for instances that track something that needs to be clean up?

The way I'd see this working is that if a class implements both interfaces, then we'll already have an instance of it from building the collection of startables, so when building the stoppables collection, we grab that instance instead of creating a new one.

Then, when scanning for eligible stoppable types, we only need to create instances of classes that implement just `IWantToRunWhenEndpointStops` and not both.

**Comment by SimonCropp** [comment]
given IWantToRunWhenEndpointStops is a hack to get around a flaw in the host design i dont think it is worth doing any cleanup

**Comment by andreasohlund** [comment]
I'm with @bording and @SimonCropp , I don't see ROI for a split, ok to close @colin-higgins ?

**Comment by colin-higgins** [comment]
Closing. :+1:
