### ISSUE TITLE
StartableAndStoppableRunner is not actually concurrent

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.Host#73]
While working on https://github.com/Particular/NServiceBus.Host/pull/72 @bording was looking into refactoring it to be async/await. 

There are a couple tests that indicate this:
 - [Should_throw_if_startable_fails_synchronously](https://github.com/Particular/NServiceBus.Host/blob/develop/src%2FNServiceBus.Hosting.Tests%2FStartablesAndStoppables%2FStartableAndStoppableRunnerTests.cs#L37)
 - [Should_throw_if_startable_fails_asynchronously](https://github.com/Particular/NServiceBus.Host/blob/develop/src%2FNServiceBus.Hosting.Tests%2FStartablesAndStoppables%2FStartableAndStoppableRunnerTests.cs#L51)

If they start concurrently, then theoretically all of them should be started, but whichever startable errors out prevents the next ones from starting.

**Comment by bording** [comment]
It also appears that [Should_throw_if_startable_fails_asynchronously](https://github.com/Particular/NServiceBus.Host/blob/develop/src%2FNServiceBus.Hosting.Tests%2FStartablesAndStoppables%2FStartableAndStoppableRunnerTests.cs#L51) is missing a `startable2` like the synchronous version has.

Regarding the refactoring I was considering, this is what I came up with:

```
public Task Start(IMessageSession session)
{
    var startableTasks = wantToRunWhenBusStartsAndStops.Select(s =>
    {
        return Task.Run(async () =>
        {
            var startableName = s.GetType().AssemblyQualifiedName;

            try
            {
                var task = s.Start(session).ThrowIfNull();

                await task;

                thingsRanAtStartup.Add(s);
                Log.DebugFormat("Started {0}.", startableName);
            }
            catch (Exception ex)
            {
                Log.Error($"Startup task {startableName} failed to complete.", ex);
                throw;
            }
        });
    });

    return Task.WhenAll(startableTasks);
}
```

This seems to have the desired concurrently executing behavior, but that lead me to the apparent inconsistency in the tests.

**Comment by timbussmann** [comment]
From the docs:

> Since Start() executes all IWantToRunWhenEndpointStartsAndStops asynchronously but not on its dedicated thread. It is the responsibility of the implementing class to execute its operations in parallel if needed (i.e. for CPU bound work). Failure to do so will prevent the bus from being started.

We never state something about parallel execution. The problem rather seems to be the fact that if you throw in a non-async method, the exception is immediately returned to the caller which means we need to wrap the call to `Start` in a try/catch?

> Failure to do so will prevent the bus from being started.

is this still true?

**Comment by boblangley** [comment]
@Particular/tf-v6-launch-plat-dev Please review: I think we should include this in scope for v6.

**Comment by colin-higgins** [comment]
@timbussmann: https://github.com/Particular/NServiceBus.Host/pull/64#discussion_r57149811

That made me think the intent was that each were concurrent. If it is not the intent, then alright.

I think we definitely want to stop the bus if a start method fails. I guess a test should be written that delays task1 by a few seconds before it throws an error and lets task2 complete immediately if we want to test concurrency.

That way, if we want concurrency, we can make sure later starts get called successfully and the endpoint still does not successfully start. That would bring into question though whether we should call Stop methods for anything that succeeds in start when the endpoint crashes....

**Comment by bording** [comment]
I think we need to decide what the intent is and then align things to match. At this point it seems like some aspects are saying we want to start them all then wait for them to finish, and other places seem to indicate otherwise!

**Comment by distantcam** [comment]
> If they start concurrently, then theoretically all of them should be started, but whichever startable errors out prevents the next ones from starting.

That's not how it works. Starting them concurrently means they all start together, not one after another. Because of the single thread they will usually execute in order but if any give up the thread (using `Task.Yield()` for example) then the next task will be started.

For me the issue is should each startup task be atomic, or should they be allowed to interleave their instructions. I'd vote for atomic as it's the simpler model to understand, unless there's a compelling need to not make them atomic. Same for shutdown tasks.

**Comment by distantcam** [comment]
Actually, it's worse than that because the tasks are already given to us, presumably in an already started state. So we're forced to accept the tasks are concurrent.

**Comment by danielmarbach** [comment]
@colin-higgins @bording can we get on a call?

**Comment by danielmarbach** [comment]
What the initial intent was:

If any of the concurrently executed startup implementations throw the start phase of the endpoint will not successfully complete. And exception is thrown to the caller of endpoint start.

We explicitly do not want to enforce parallelism but asynchronous and concurrent execution.

Yes there is a runtime difference between

```
static async Task ThrowAsync() {
   throw new Exception();
}
```

and

```
static Task ThrowSync() {
   throw new Exception();
}
```

The first version will rethrow the exception when the task is awaited (i.ex. in the `Task.WhenAll`). The second version will throw when the enumerable is yielded. That behavior is desired. Since when we have a sync exception there is no need to continue, we can directly throw back to the callling throw while yielding the startup tasks. In the async version we can only now the outcome of the tasks when it is awaited. 

So the like @distantcam the decision should be:

Should each startup task be executed asynchronous but we await the outcome of the task sequentially or do we stay with the current approach?

**Comment by colin-higgins** [comment]
In talking with @danielmarbach, The tests and behavior make sense to me. We should not be enforcing parallelism. I am going to add a comment into the two tests to detail the behavior this is testing, which is the behavior difference between sync and async yields.

**Comment by danielmarbach** [comment]
@colin-higgins What do we do with this issue? I propose we close it.

**Comment by colin-higgins** [comment]
Agreed
