### ISSUE TITLE
Support GMSA accounts 

### ISSUE THREAD

**Issue by sfarmar** [Particular/NServiceBus.Host#93]
Customer request:

> Description: I want the Windows Service that NServiceBus.Host.exe creates
> to be executed as a Group Managed Service Account. In Windows Server 2012,
> you can create a special account in Active Directory called a Group Managed
> Service Account (gMSA). You can use this account to host Windows Services,
> IIS App Pools, Scheduled Tasks, and more. The advantage of using a gMSA is
> that you don't have to know the password. In fact, no one knows the
> password. When an administrator of a server creates a Windows Service
> using services.msc, he (or she) can click on the login tab, type the gMSA's
> UPN and leave the password blank. The server (if it is permitted to do so)
> will retrieve the managed password from Active Directory. The password is
> automatically changed and refreshed on a scheduled basis.
> 
> 
> 
> We run as many services as we can using gMSA's.
> 
> 
> 
> You can read more about gMSA's here:
> https://blogs.technet.microsoft.com/askpfeplat/2012/12/16/windows-server-2012-group-managed-service-accounts/
> 

see also: https://github.com/Particular/ServiceControl/issues/768

**Comment by SimonCropp** [comment]
@sfarmar is it a valid workaround to point them to selfhosting?

**Comment by sfarmar** [comment]
It could be an option 

[Adding the link to the sample](http://docs.particular.net/samples/hosting/self-hosting/)

**Comment by robv8r** [comment]
Self Hosting is an option.  However, it would require additional custom development and additional deployment scripts to install.  Then it would require additional steps to permit the gMSA access to the resources it needs.  In comparision, NServiceBusHost.exe does all that out-of-the-box.

It's not an insurmountable task, but doing this is inconvenient and time consuming.  NServiceBus charges a large amount for its software because it is an elegant and straight-forward solution.  It scales well, is fault tolerant, is highly secure, and hides the complexity of messaging from the developer so that the developer can concentrate on solving business problems.

Asking a potential customer to write custom code to host, deploy, configure, and secure the application negates many of the advantages that NServiceBus is supposed to provide out of the box.

**Comment by andreasohlund** [comment]
Would it work to use sc.exe to install the host instead?(https://blog.stangroome.com/2013/07/28/avoid-password-management-with-group-managed-service-accounts/)

**Comment by gbiellem** [comment]
@andreasohlund IMO this is a bug in the host.  From what I can see the only thing preventing it from working is that the host install assumes when no password is specified the service account is LocalSystem even if you've specified an alternate username

See https://github.com/Particular/NServiceBus.Host/blob/master/src/NServiceBus.Hosting.Windows/Program.cs#L86

This is wrong for not just GMSA accounts but also for other built in accounts such as NetworkService or LocalService.

I've been working on the GMSA for ServiceControl and we had a similar bad assumption in our account validation. Once it was removed and we allowed null passwords the service registration works without any other code changes

**Comment by gbiellem** [comment]
I had a deeper look - The topshelf.dll using by the host doesn't allow a null password so that would also need to be fixed

**Comment by andreasohlund** [comment]
We use an old forked version of Topshelf, https://github.com/Particular/Topshelf, but patching it should be doable

**Comment by gbiellem** [comment]
@andreasohlund  I've put together a PR for GMSA against the current host. Tested it on a Win 2012 AD domain.

**Comment by gbiellem** [comment]
@andreasohlund  as you [requested](https://github.com/Particular/NServiceBus.Host/pull/96#issuecomment-240051923) I've opened a new PR targeting release 7 branch and closed the old one.

**Comment by indualagarsamy** [comment]
@gbiellem - can this issue be closed?

**Comment by gbiellem** [comment]
Yeah I think so.

**Comment by danielmarbach** [comment]
Implemented in https://github.com/Particular/NServiceBus.Host/pull/98
